config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'
  get 'relationships/create'
  get 'relationships/destroy'

  resources :relationships, only: [:create, :destroy]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :topics, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :comments, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :topics do
    resources :comments
    post :confirm, on: :collection
  end

  resources :conversations do
    resources :messages
  end

  root 'top#index'

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all.order(created_at: :desc)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice: "投稿しました！"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @topic.update(topics_params)
    redirect_to topics_path
  end

  def destroy
    @topic.destroy
    redirect_to topics_path
  end

  private
    def topics_params
      params.require(:topic).permit(:content, :image)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :画像 %>
  　<%= image_tag @topic.image if @topic.image %>
  <%= f.file_field :image, class: 'form-control' %>
  <br>
  <%= f.label :投稿内容 %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "タイムラインに戻る", topics_path %>

app/views/topics/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>投稿を編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h2>タイムライン </h2>
    <%= link_to "新しく投稿する", new_topic_path, class: 'btn btn-primary' %>

    <% @topics.each do |topic| %>
    <div class="row">
      <div class="profile_img">
      <%= profile_img(topic.user) if profile_img(topic.user) %>
      </div>
      <p><%= topic.user.name if topic.user %>が投稿しました。</p>
      <%= link_to topic_path(topic) do %>
      <h4><strong><%= topic.content %></strong></h4>
      <div class="topic_image">
      <p><%= image_tag topic.image %></p>
      </div>
      <% end %>
      <br>
      <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>投稿する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="topic-text">
      <p class="left"><%= link_to '戻る', topics_path %></p>
      <p class="left"><strong>内容</strong></p>
      <p><%= image_tag @topic.image %></p>
      <p class="left"><%= @topic.content %></p>
      <% if current_user.id == @topic.user_id %>
        <p class="right">
          <%= link_to '編集', edit_topic_path(@topic) %>
        </p>
      <% end %>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p class="left"><strong>コメント一覧</strong></p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
  </div>
</div>