config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'
  get 'relationships/create'
  get 'relationships/destroy'

  resources :relationships, only: [:create, :destroy]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :topics, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :comments, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :topics do
    resources :comments
    post :confirm, on: :collection
  end

  resources :conversations do
    resources :messages
  end

  root 'top#index'

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, :omniauthable
  mount_uploader :avatar, AvatarUploader

  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
        name:     auth.extra.raw_info.name,
        provider: auth.provider,
        uid:      auth.uid,
        email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        image_url:   auth.info.image,
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @followers = @user.followers
    @followed_users = @user.followed_users
  end

  def edit
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "つながりを解除", class: "btn btn-large" %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザー一覧</h2>
  <% @users.each do |user| %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
        <%= profile_img(user) %>
        <ul style="list-style:none;">
          <li><%= link_to user.name, user %></li>
          <li><% if user.id != current_user.id %></li>
          <li><%= link_to 'メッセージを送る', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%></li>
        </ul>
        <%= render partial: 'follow_form', locals: { user: user } if signed_in?   %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<section class="users container-fluid">
  <h2>ユーザー情報</h2>
  <div class="container-child col-md-3 col-sm-6">
    <p class="left"><%= link_to '戻る', users_path %></p>
    <ul style="list-style:none;">
      <li><%= profile_img(@user) if profile_img(@user) %></li>
      <li><strong>ユーザー名</p></li>
      <li><%= @user.name %></li>
      <li><%= @user.email %></li>
    </ul>
  </div>
</section>

<section class="followers container-fluid">
  <div class="row">
    <h2>フォロワー一覧</h2>
    <div class="col-md-3 col-sm-6">
      <div id="followers_area">
        <%= render partial: 'users/followers/index', locals: { followers: @followers, user: @user } %>
      </div>
    </div>
  </div>
</section>

<section class="followed_users container-fluid">
  <div class="row">
    <h2>フォロイー一覧</h2>
    <div class="col-md-3 col-sm-6">
      <div id="followed_users_area">
        <%= render partial: 'users/followed_users/index', locals: { followed_users: @followed_users, user: @user } %>
      </div>
    </div>
  </div>
</section>